### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by zhaojiaTech** [lingjie0206/Neural_Actor_Main_Code#1]
Thank you for sharing code of your awesome work. This may be a dumb question but I encountered the the following error when doing pip install -r requirements.txt. (I changed git+https to git+ssh in requirements.txt since password authentication is no longer supported by github)

`Collecting git+ssh://****@github.com/MultiPath/fairseq-stable.git (from -r requirements.txt (line 21))
  Cloning ssh://****@github.com/MultiPath/fairseq-stable.git to /tmp/pip-req-build-d73g8hcw
  Running command git clone -q 'ssh://****@github.com/MultiPath/fairseq-stable.git' /tmp/pip-req-build-d73g8hcw
  Resolved ssh://****@github.com/MultiPath/fairseq-stable.git to commit 8aa06aa03b596de58d106d3f55ff43e2b9aa0b80
  Running command git submodule update --init --recursive -q
  ERROR: Repository not found.
  fatal: Could not read from remote repository.
`

`
  Please make sure you have the correct access rights
  and the repository exists.
  fatal: clone of 'https://github.com/myleott/transformers.git' into submodule path '/tmp/pip-req-build-d73g8hcw/fairseq/models/huggingface/transformers' failed
  Failed to clone 'fairseq/models/huggingface/transformers'. Retry scheduled
  ERROR: Repository not found.
  fatal: Could not read from remote repository.
`

`
  Please make sure you have the correct access rights
  and the repository exists.
  fatal: clone of 'https://github.com/myleott/transformers.git' into submodule path '/tmp/pip-req-build-d73g8hcw/fairseq/models/huggingface/transformers' failed
  Failed to clone 'fairseq/models/huggingface/transformers' a second time, aborting
WARNING: Discarding git+ssh://****@github.com/MultiPath/fairseq-stable.git. Command errored out with exit status 1: git submodule update --init --recursive -q Check the logs for full command output.
ERROR: Command errored out with exit status 1: git submodule update --init --recursive -q Check the logs for full command output.
`
 
Is there a work around to this problem?

**Comment by MultiPath** [comment]
It should be working now. Please have a try again.

There was one dependency removed from Github. You could also try installing fairseq by cloning:
```
git clone --recursive https://github.com/MultiPath/fairseq-stable.git
cd fairseq-stable
pip install .
```
