### ISSUE TITLE
ImportError: cannot import name 'with_torch_seed' from 'fairseq.utils'

### ISSUE THREAD

**Issue by anzisheng** [lingjie0206/Neural_Actor_Main_Code#5]
when I run the train.py, I meet across an error：“ImportError: cannot import name 'with_torch_seed' from 'fairseq.utils'”。 Anyone can tell me how should I solver it ?

**Comment by lingjie0206** [comment]
Hi, can you verify what fairseq version did you install?
You can also try ``pip install fairseq==0.10.2``
