### ISSUE TITLE
Some question about pre-processing my own datasets.

### ISSUE THREAD

**Issue by NeaRBrotheR** [lingjie0206/Neural_Actor_Main_Code#7]
On [this page](https://github.com/lingjie0206/Neural_Actor_Preprocessing)

in generate_transform_files/hello_smpl_pose.py line48 https://github.com/lingjie0206/Neural_Actor_Preprocessing/blob/e48dd8824b88c95191c483f7316d3cfb170b0a64/generate_transform_files/hello_smpl_pose.py#L48

https://github.com/lingjie0206/Neural_Actor_Preprocessing/blob/e48dd8824b88c95191c483f7316d3cfb170b0a64/generate_transform_files/hello_smpl_pose.py#L8

in smpl_webuser.serialization.py , load_model only return the one variable (result),
but there use three variable to catch the return value of load_model.

I know the m is the info about smpl model , and dd means some info from smpl_webuser.serialization.py ,
but only A i don't konw what is it means.
Could you please explain this variable for me? Thanks a lout!!

**Comment by lingjie0206** [comment]
It's the transformation of joints. You may refer to the original SMPL code.
